CREATE DATABASE IF NOT EXISTS geocase_portal CHARACTER SET utf8 COLLATE utf8_general_ci; 

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON geocase_portal.* TO 'geocase_user'@'%' IDENTIFIED BY 'test'; 
